### ISSUE TITLE
NaN comparison

### ISSUE THREAD

**Issue by jystic** [ambiata/icicle#536] opened 2017-05-25 07:55 UTC
Do we have some special equality function for this?
```
=== prop_check_history_core_same_aval from test/Icicle/Test/Source/History.hs:136 ===
*** Failed! Falsifiable (after 594 tests): 
TestStuff {tsQwf = QueryWithFeature:
  Query: sqrt (- 0.8817318515559287)
  Now: statlernow
  Output: fozzy
  Type: String
  Name: statlerfeaturename
  Time: statlertimename
  Key: "stan", tsInputs = [AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -61, flavourTime = Time (1858 9 17 0 0 0s)}),VString "bart"), atTime = Time (1858 9 17 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -59, flavourTime = Time (1858 9 19 0 0 0s)}),VString "bart"), atTime = Time (1858 9 19 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -58, flavourTime = Time (1858 9 20 0 0 0s)}),VString "marge"), atTime = Time (1858 9 20 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -56, flavourTime = Time (1858 9 22 0 0 0s)}),VString "marge"), atTime = Time (1858 9 22 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -56, flavourTime = Time (1858 9 22 0 0 0s)}),VString "marge"), atTime = Time (1858 9 22 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -55, flavourTime = Time (1858 9 23 0 0 0s)}),VString "flanders"), atTime = Time (1858 9 23 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -53, flavourTime = Time (1858 9 25 0 0 0s)}),VString "barney"), atTime = Time (1858 9 25 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -51, flavourTime = Time (1858 9 27 0 0 0s)}),VString "moe"), atTime = Time (1858 9 27 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -50, flavourTime = Time (1858 9 28 0 0 0s)}),VString "moe"), atTime = Time (1858 9 28 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -50, flavourTime = Time (1858 9 28 0 0 0s)}),VString "homer"), atTime = Time (1858 9 28 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -49, flavourTime = Time (1858 9 29 0 0 0s)}),VString "moe"), atTime = Time (1858 9 29 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -47, flavourTime = Time (1858 10 1 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 1 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -47, flavourTime = Time (1858 10 1 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 1 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -45, flavourTime = Time (1858 10 3 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 3 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -44, flavourTime = Time (1858 10 4 0 0 0s)}),VString "bart"), atTime = Time (1858 10 4 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -43, flavourTime = Time (1858 10 5 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 5 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -42, flavourTime = Time (1858 10 6 0 0 0s)}),VString "lisa"), atTime = Time (1858 10 6 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -40, flavourTime = Time (1858 10 8 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 8 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -38, flavourTime = Time (1858 10 10 0 0 0s)}),VString "lisa"), atTime = Time (1858 10 10 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -36, flavourTime = Time (1858 10 12 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 12 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -36, flavourTime = Time (1858 10 12 0 0 0s)}),VString "homer"), atTime = Time (1858 10 12 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -36, flavourTime = Time (1858 10 12 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 12 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -35, flavourTime = Time (1858 10 13 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 13 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -35, flavourTime = Time (1858 10 13 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 13 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -33, flavourTime = Time (1858 10 15 0 0 0s)}),VString "moe"), atTime = Time (1858 10 15 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -31, flavourTime = Time (1858 10 17 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 17 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -31, flavourTime = Time (1858 10 17 0 0 0s)}),VString "moe"), atTime = Time (1858 10 17 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -29, flavourTime = Time (1858 10 19 0 0 0s)}),VString "lisa"), atTime = Time (1858 10 19 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -28, flavourTime = Time (1858 10 20 0 0 0s)}),VString "bart"), atTime = Time (1858 10 20 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -26, flavourTime = Time (1858 10 22 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 22 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -25, flavourTime = Time (1858 10 23 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 23 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -25, flavourTime = Time (1858 10 23 0 0 0s)}),VString "barney"), atTime = Time (1858 10 23 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -25, flavourTime = Time (1858 10 23 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 23 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -23, flavourTime = Time (1858 10 25 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 25 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -22, flavourTime = Time (1858 10 26 0 0 0s)}),VString "bart"), atTime = Time (1858 10 26 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -21, flavourTime = Time (1858 10 27 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 27 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -19, flavourTime = Time (1858 10 29 0 0 0s)}),VString "moe"), atTime = Time (1858 10 29 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -17, flavourTime = Time (1858 10 31 0 0 0s)}),VString "moe"), atTime = Time (1858 10 31 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -16, flavourTime = Time (1858 11 1 0 0 0s)}),VString "marge"), atTime = Time (1858 11 1 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -16, flavourTime = Time (1858 11 1 0 0 0s)}),VString "maggie"), atTime = Time (1858 11 1 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -15, flavourTime = Time (1858 11 2 0 0 0s)}),VString "lisa"), atTime = Time (1858 11 2 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -14, flavourTime = Time (1858 11 3 0 0 0s)}),VString "homer"), atTime = Time (1858 11 3 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -14, flavourTime = Time (1858 11 3 0 0 0s)}),VString "lisa"), atTime = Time (1858 11 3 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -13, flavourTime = Time (1858 11 4 0 0 0s)}),VString "bart"), atTime = Time (1858 11 4 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -11, flavourTime = Time (1858 11 6 0 0 0s)}),VString "flanders"), atTime = Time (1858 11 6 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -10, flavourTime = Time (1858 11 7 0 0 0s)}),VString "moe"), atTime = Time (1858 11 7 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -10, flavourTime = Time (1858 11 7 0 0 0s)}),VString "barney"), atTime = Time (1858 11 7 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -10, flavourTime = Time (1858 11 7 0 0 0s)}),VString "flanders"), atTime = Time (1858 11 7 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -8, flavourTime = Time (1858 11 9 0 0 0s)}),VString "bart"), atTime = Time (1858 11 9 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -7, flavourTime = Time (1858 11 10 0 0 0s)}),VString "homer"), atTime = Time (1858 11 10 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -5, flavourTime = Time (1858 11 12 0 0 0s)}),VString "barney"), atTime = Time (1858 11 12 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -5, flavourTime = Time (1858 11 12 0 0 0s)}),VString "moe"), atTime = Time (1858 11 12 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -4, flavourTime = Time (1858 11 13 0 0 0s)}),VString "marge"), atTime = Time (1858 11 13 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -2, flavourTime = Time (1858 11 15 0 0 0s)}),VString "homer"), atTime = Time (1858 11 15 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 0, flavourTime = Time (1858 11 17 0 0 0s)}),VString "moe"), atTime = Time (1858 11 17 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 2, flavourTime = Time (1858 11 19 0 0 0s)}),VString "moe"), atTime = Time (1858 11 19 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 3, flavourTime = Time (1858 11 20 0 0 0s)}),VString "homer"), atTime = Time (1858 11 20 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 5, flavourTime = Time (1858 11 22 0 0 0s)}),VString "moe"), atTime = Time (1858 11 22 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 7, flavourTime = Time (1858 11 24 0 0 0s)}),VString "marge"), atTime = Time (1858 11 24 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 9, flavourTime = Time (1858 11 26 0 0 0s)}),VString "barney"), atTime = Time (1858 11 26 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 10, flavourTime = Time (1858 11 27 0 0 0s)}),VString "moe"), atTime = Time (1858 11 27 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 11, flavourTime = Time (1858 11 28 0 0 0s)}),VString "marge"), atTime = Time (1858 11 28 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 13, flavourTime = Time (1858 11 30 0 0 0s)}),VString "barney"), atTime = Time (1858 11 30 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 15, flavourTime = Time (1858 12 2 0 0 0s)}),VString "barney"), atTime = Time (1858 12 2 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 17, flavourTime = Time (1858 12 4 0 0 0s)}),VString "bart"), atTime = Time (1858 12 4 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 18, flavourTime = Time (1858 12 5 0 0 0s)}),VString "moe"), atTime = Time (1858 12 5 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 18, flavourTime = Time (1858 12 5 0 0 0s)}),VString "bart"), atTime = Time (1858 12 5 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 18, flavourTime = Time (1858 12 5 0 0 0s)}),VString "flanders"), atTime = Time (1858 12 5 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 20, flavourTime = Time (1858 12 7 0 0 0s)}),VString "lisa"), atTime = Time (1858 12 7 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 21, flavourTime = Time (1858 12 8 0 0 0s)}),VString "marge"), atTime = Time (1858 12 8 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 23, flavourTime = Time (1858 12 10 0 0 0s)}),VString "maggie"), atTime = Time (1858 12 10 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 25, flavourTime = Time (1858 12 12 0 0 0s)}),VString "moe"), atTime = Time (1858 12 12 0 0 0s)}], tsTime = Time (1858 12 14 0 0 0s), tsCore = Program {inputType = StringT, factValName = Name {nameHash = 8985580063086465620, nameBase = NameMod (Variable "core") (NameBase (Variable "0"))}, factIdName = Name {nameHash = 8985580063069689063, nameBase = NameMod (Variable "core") (NameBase (Variable "1"))}, factTimeName = Name {nameHash = 8985580063120021362, nameBase = NameMod (Variable "core") (NameBase (Variable "2"))}, snaptimeName = Name {nameHash = 8985580063103240589, nameBase = NameMod (Variable "core") (NameBase (Variable "3"))}, precomps = [(Name {nameHash = 8985580063153571864, nameBase = NameMod (Variable "core") (NameBase (Variable "4"))},XApp () (XPrim () (PrimMinimal (PrimBuiltinFun (PrimBuiltinMath PrimBuiltinSqrt)))) (XApp () (XPrim () (PrimMinimal (PrimArithUnary PrimArithNegate ArithDoubleT))) (XValue () DoubleT (VDouble 0.8817318515559287))))], streams = [], postcomps = [], returns = [(OutputName "fozzy",XVar () (Name {nameHash = 8985580063153571864, nameBase = NameMod (Variable "core") (NameBase (Variable "4"))}))]}, tsAval = Program {input = StringT, bindtime = Name {nameHash = 8985580063103240589, nameBase = NameMod (Variable "core") (NameBase (Variable "3"))}, statements = Let (Name {nameHash = 8985580063153571864, nameBase = NameMod (Variable "core") (NameBase (Variable "4"))}) (XApp () (XPrim () (PrimMinimal (PrimBuiltinFun (PrimBuiltinMath PrimBuiltinSqrt)))) (XApp () (XPrim () (PrimMinimal (PrimArithUnary PrimArithNegate ArithDoubleT))) (XValue () DoubleT (VDouble 0.8817318515559287)))) (Block [Block [],Block [Block [ForeachFacts (FactBinds {factBindTime = Name {nameHash = 8985580063120021362, nameBase = NameMod (Variable "core") (NameBase (Variable "2"))}, factBindId = Name {nameHash = 8985580063069689063, nameBase = NameMod (Variable "core") (NameBase (Variable "1"))}, factBindValue = [(Name {nameHash = 8985580063086465620, nameBase = NameMod (Variable "core") (NameBase (Variable "0"))},PairT StringT TimeT)]}) (PairT StringT TimeT) FactLoopNew (Block []),Block []],Block [Block [],Block [Output (OutputName "fozzy") DoubleT [(XVar () (Name {nameHash = 8985580063153571864, nameBase = NameMod (Variable "core") (NameBase (Variable "4"))}),DoubleT)]]]]])}}
feature statlerfeaturename
~> sqrt (- 0.8817318515559287)
[AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -61, flavourTime = Time (1858 9 17 0 0 0s)}),VString "bart"), atTime = Time (1858 9 17 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -59, flavourTime = Time (1858 9 19 0 0 0s)}),VString "bart"), atTime = Time (1858 9 19 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -58, flavourTime = Time (1858 9 20 0 0 0s)}),VString "marge"), atTime = Time (1858 9 20 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -56, flavourTime = Time (1858 9 22 0 0 0s)}),VString "marge"), atTime = Time (1858 9 22 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -56, flavourTime = Time (1858 9 22 0 0 0s)}),VString "marge"), atTime = Time (1858 9 22 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -55, flavourTime = Time (1858 9 23 0 0 0s)}),VString "flanders"), atTime = Time (1858 9 23 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -53, flavourTime = Time (1858 9 25 0 0 0s)}),VString "barney"), atTime = Time (1858 9 25 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -51, flavourTime = Time (1858 9 27 0 0 0s)}),VString "moe"), atTime = Time (1858 9 27 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -50, flavourTime = Time (1858 9 28 0 0 0s)}),VString "moe"), atTime = Time (1858 9 28 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -50, flavourTime = Time (1858 9 28 0 0 0s)}),VString "homer"), atTime = Time (1858 9 28 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -49, flavourTime = Time (1858 9 29 0 0 0s)}),VString "moe"), atTime = Time (1858 9 29 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -47, flavourTime = Time (1858 10 1 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 1 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -47, flavourTime = Time (1858 10 1 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 1 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -45, flavourTime = Time (1858 10 3 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 3 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -44, flavourTime = Time (1858 10 4 0 0 0s)}),VString "bart"), atTime = Time (1858 10 4 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -43, flavourTime = Time (1858 10 5 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 5 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -42, flavourTime = Time (1858 10 6 0 0 0s)}),VString "lisa"), atTime = Time (1858 10 6 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -40, flavourTime = Time (1858 10 8 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 8 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -38, flavourTime = Time (1858 10 10 0 0 0s)}),VString "lisa"), atTime = Time (1858 10 10 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -36, flavourTime = Time (1858 10 12 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 12 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -36, flavourTime = Time (1858 10 12 0 0 0s)}),VString "homer"), atTime = Time (1858 10 12 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -36, flavourTime = Time (1858 10 12 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 12 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -35, flavourTime = Time (1858 10 13 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 13 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -35, flavourTime = Time (1858 10 13 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 13 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -33, flavourTime = Time (1858 10 15 0 0 0s)}),VString "moe"), atTime = Time (1858 10 15 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -31, flavourTime = Time (1858 10 17 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 17 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -31, flavourTime = Time (1858 10 17 0 0 0s)}),VString "moe"), atTime = Time (1858 10 17 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -29, flavourTime = Time (1858 10 19 0 0 0s)}),VString "lisa"), atTime = Time (1858 10 19 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -28, flavourTime = Time (1858 10 20 0 0 0s)}),VString "bart"), atTime = Time (1858 10 20 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -26, flavourTime = Time (1858 10 22 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 22 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -25, flavourTime = Time (1858 10 23 0 0 0s)}),VString "flanders"), atTime = Time (1858 10 23 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -25, flavourTime = Time (1858 10 23 0 0 0s)}),VString "barney"), atTime = Time (1858 10 23 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -25, flavourTime = Time (1858 10 23 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 23 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -23, flavourTime = Time (1858 10 25 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 25 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -22, flavourTime = Time (1858 10 26 0 0 0s)}),VString "bart"), atTime = Time (1858 10 26 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -21, flavourTime = Time (1858 10 27 0 0 0s)}),VString "maggie"), atTime = Time (1858 10 27 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -19, flavourTime = Time (1858 10 29 0 0 0s)}),VString "moe"), atTime = Time (1858 10 29 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -17, flavourTime = Time (1858 10 31 0 0 0s)}),VString "moe"), atTime = Time (1858 10 31 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -16, flavourTime = Time (1858 11 1 0 0 0s)}),VString "marge"), atTime = Time (1858 11 1 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -16, flavourTime = Time (1858 11 1 0 0 0s)}),VString "maggie"), atTime = Time (1858 11 1 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -15, flavourTime = Time (1858 11 2 0 0 0s)}),VString "lisa"), atTime = Time (1858 11 2 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -14, flavourTime = Time (1858 11 3 0 0 0s)}),VString "homer"), atTime = Time (1858 11 3 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -14, flavourTime = Time (1858 11 3 0 0 0s)}),VString "lisa"), atTime = Time (1858 11 3 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -13, flavourTime = Time (1858 11 4 0 0 0s)}),VString "bart"), atTime = Time (1858 11 4 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -11, flavourTime = Time (1858 11 6 0 0 0s)}),VString "flanders"), atTime = Time (1858 11 6 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -10, flavourTime = Time (1858 11 7 0 0 0s)}),VString "moe"), atTime = Time (1858 11 7 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -10, flavourTime = Time (1858 11 7 0 0 0s)}),VString "barney"), atTime = Time (1858 11 7 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -10, flavourTime = Time (1858 11 7 0 0 0s)}),VString "flanders"), atTime = Time (1858 11 7 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -8, flavourTime = Time (1858 11 9 0 0 0s)}),VString "bart"), atTime = Time (1858 11 9 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -7, flavourTime = Time (1858 11 10 0 0 0s)}),VString "homer"), atTime = Time (1858 11 10 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -5, flavourTime = Time (1858 11 12 0 0 0s)}),VString "barney"), atTime = Time (1858 11 12 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -5, flavourTime = Time (1858 11 12 0 0 0s)}),VString "moe"), atTime = Time (1858 11 12 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -4, flavourTime = Time (1858 11 13 0 0 0s)}),VString "marge"), atTime = Time (1858 11 13 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = -2, flavourTime = Time (1858 11 15 0 0 0s)}),VString "homer"), atTime = Time (1858 11 15 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 0, flavourTime = Time (1858 11 17 0 0 0s)}),VString "moe"), atTime = Time (1858 11 17 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 2, flavourTime = Time (1858 11 19 0 0 0s)}),VString "moe"), atTime = Time (1858 11 19 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 3, flavourTime = Time (1858 11 20 0 0 0s)}),VString "homer"), atTime = Time (1858 11 20 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 5, flavourTime = Time (1858 11 22 0 0 0s)}),VString "moe"), atTime = Time (1858 11 22 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 7, flavourTime = Time (1858 11 24 0 0 0s)}),VString "marge"), atTime = Time (1858 11 24 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 9, flavourTime = Time (1858 11 26 0 0 0s)}),VString "barney"), atTime = Time (1858 11 26 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 10, flavourTime = Time (1858 11 27 0 0 0s)}),VString "moe"), atTime = Time (1858 11 27 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 11, flavourTime = Time (1858 11 28 0 0 0s)}),VString "marge"), atTime = Time (1858 11 28 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 13, flavourTime = Time (1858 11 30 0 0 0s)}),VString "barney"), atTime = Time (1858 11 30 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 15, flavourTime = Time (1858 12 2 0 0 0s)}),VString "barney"), atTime = Time (1858 12 2 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 17, flavourTime = Time (1858 12 4 0 0 0s)}),VString "bart"), atTime = Time (1858 12 4 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 18, flavourTime = Time (1858 12 5 0 0 0s)}),VString "moe"), atTime = Time (1858 12 5 0 0 0s)},AsAt {aTest suite test: FAIL
Test suite logged to: dist/test/icicle-0.0.1-test.log
tFact = (BubbleGumFact (Flavour {flavourId = 18, flavourTime = Time (1858 12 5 0 0 0s)}),VString "bart"), atTime = Time (1858 12 5 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 18, flavourTime = Time (1858 12 5 0 0 0s)}),VString "flanders"), atTime = Time (1858 12 5 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 20, flavourTime = Time (1858 12 7 0 0 0s)}),VString "lisa"), atTime = Time (1858 12 7 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 21, flavourTime = Time (1858 12 8 0 0 0s)}),VString "marge"), atTime = Time (1858 12 8 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 23, flavourTime = Time (1858 12 10 0 0 0s)}),VString "maggie"), atTime = Time (1858 12 10 0 0 0s)},AsAt {atFact = (BubbleGumFact (Flavour {flavourId = 25, flavourTime = Time (1858 12 12 0 0 0s)}),VString "moe"), atTime = Time (1858 12 12 0 0 0s)}]
Program (core$0 : String, core$1 : FactIdentifier, core$2 : Time, core$3 : SNAPSHOT_TIME)
Precomputations:
  core$4               = sqrt# (negate# (0.8817318515559287))

Streams:
  

Postcomputations:


Returning:
  fozzy                = core$4

core$3 = TIME
let core$4 = sqrt# (negate# (0.8817318515559287));

for_facts (core$2, core$1, core$0) in new
{
  
}


output fozzy (core$4);
[(OutputName "fozzy",VDouble NaN)] /= [(OutputName "fozzy",VDouble NaN)]
```

**Comment by tranma** [comment] 2017-05-25 11:10
duplicate of https://github.com/ambiata/icicle/issues/385
we don't do anything about this at the moment.

**Closed** 2017-06-13 02:38 UTC
